
language: cpp

os: linux

compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install cppcheck -y
  - sudo apt-get install python2.7 -y
  - sudo apt-get install g++-9 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  - sudo apt-get install libboost-all-dev -y
  - curl -OL https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip
  - unzip protoc-3.6.1-linux-x86_64.zip -d protoc3
  - sudo cp -r protoc3/bin/* /usr/local/bin/
  - sudo cp -r protoc3/include/* /usr/local/include/
  - sudo chown $USER /usr/local/bin/protoc
  - sudo chown -R $USER /usr/local/include/google
  - sudo ldconfig
  - CMAKE_VERSION=3.15.4
  - CMAKE_VERSION_DIR=v3.15
  - CMAKE_OS=Linux-x86_64
  - CMAKE_TAR=cmake-$CMAKE_VERSION-$CMAKE_OS.tar.gz
  - CMAKE_URL=http://www.cmake.org/files/$CMAKE_VERSION_DIR/$CMAKE_TAR
  - CMAKE_DIR=$(pwd)/cmake-$CMAKE_VERSION
  - wget --quiet $CMAKE_URL
  - mkdir -p $CMAKE_DIR
  - tar --strip-components=1 -xzf $CMAKE_TAR -C $CMAKE_DIR
  - export PATH=$CMAKE_DIR/bin:$PATH

script:
#  - ./linters/run.sh --local
  - mkdir build
  - cd build
  - cmake ../
  - make
  - ./test