
language: cpp

os: linux

compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install cppcheck -y
  - sudo apt-get install python2.7 -y
  - sudo apt-get install g++-9 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
  - sudo apt-get install valgrind -y
  - sudo apt-get install autoconf automake libtool libboost-all-dev -y
  # - sudo apt-get install build-essential python-dev autotools-dev libicu-dev build-essential libbz2-dev libboost-all-dev -y
  # - wget -O boost_1_71_0.tar.gz https://sourceforge.net/projects/boost/files/boost/1.71.0.beta1/boost_1_71_0_b1.tar.gz/download
  # - tar xzvf boost_1_71_0.tar.gz
  # - cd boost_1_71_0/
  # - ./bootstrap.sh --prefix=/usr/
  # - ./b2
  # - sudo ./b2 install
  # - cd ..
  - curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.11.0/protobuf-cpp-3.11.0.tar.gz
  - tar --strip-components=1 -xzf protobuf-cpp-3.11.0.tar.gz -C proto3
  - cd protoc3
  - ./configure
  - make -j2
  - make -j2 check
  - sudo make -j2 install
  - sudo ldconfig
  - cd ..
  - CMAKE_VERSION=3.15.4
  - CMAKE_VERSION_DIR=v3.15
  - CMAKE_OS=Linux-x86_64
  - CMAKE_TAR=cmake-$CMAKE_VERSION-$CMAKE_OS.tar.gz
  - CMAKE_URL=http://www.cmake.org/files/$CMAKE_VERSION_DIR/$CMAKE_TAR
  - CMAKE_DIR=$(pwd)/cmake-$CMAKE_VERSION
  - wget --quiet $CMAKE_URL
  - mkdir -p $CMAKE_DIR
  - tar --strip-components=1 -xzf $CMAKE_TAR -C $CMAKE_DIR
  - export PATH=$CMAKE_DIR/bin:$PATH

script:
  - ./linters/run.sh --local
  - mkdir build
  - cd build
  - cmake ../
  - make
  - ./test
  - bash <(curl -s https://codecov.io/bash)